# Generated by Django 4.2 on 2023-05-20 16:44

from random import randint

from django.core.files import File
from django.db import migrations


def create_dummy_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Inventory = apps.get_model("inventory", "Inventory")
    Supplier = apps.get_model("supplier", "Supplier")

    User.objects.create_superuser("superuser", "superuser@superuser.com", "superuser")

    with open("test.jpg", "rb") as f:
        for i in range(3):
            supplier = Supplier.objects.create(name=f"Supplier {i}")
            for j in range(10):
                stock_number = randint(0, 10)
                Inventory.objects.create(
                    name=f"Inventory {i}{j}",
                    supplier=supplier,
                    img=File(f),
                    stock=stock_number,
                    availability=False if stock_number == 0 else True,
                )


def revert_create_dummy_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventory_inventory_inventory_availability_check"),
        ("supplier", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_dummy_data, revert_create_dummy_data)]
